### PR TITLE
fix tests for non China based people

### LINKED ISSUE #268: Failing tests
I encountered issue with running `go test` in the project's root. Various tests failed for me.

**Example:**

`traveler_unit_test.go`, function `TestCarbon_SubNanoseconds`:

I expected the test to pass, but it didn't:

```
Running tool: /usr/local/go/bin/go test -timeout 30s -run ^TestCarbon_SubNanoseconds$ github.com/dromara/carbon/v2

--- FAIL: TestCarbon_SubNanoseconds (0.00s)
    --- FAIL: TestCarbon_SubNanoseconds/case2 (0.00s)
        /home/andreas/carbon/traveler_unit_test.go:2925: 
            	Error Trace:	/home/andreas/carbon/traveler_unit_test.go:2925
            	Error:      	Not equal: 
            	            	expected: "2020-08-05 13:14:15.222222221 +0800 CST"
            	            	actual  : "2020-08-05 13:14:15.222222221 +0200 CEST"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1 +1 @@
            	            	-2020-08-05 13:14:15.222222221 +0800 CST
            	            	+2020-08-05 13:14:15.222222221 +0200 CEST
            	Test:       	TestCarbon_SubNanoseconds/case2
            	Messages:   	SubNanoseconds()
    --- FAIL: TestCarbon_SubNanoseconds/case3 (0.00s)
        /home/andreas/carbon/traveler_unit_test.go:2925: 
            	Error Trace:	/home/andreas/carbon/traveler_unit_test.go:2925
            	Error:      	Not equal: 
            	            	expected: "2020-08-05 13:14:15.22222222 +0800 CST"
            	            	actual  : "2020-08-05 13:14:15.22222222 +0200 CEST"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -1 +1 @@
            	            	-2020-08-05 13:14:15.22222222 +0800 CST
            	            	+2020-08-05 13:14:15.22222222 +0200 CEST
            	Test:       	TestCarbon_SubNanoseconds/case3
            	Messages:   	SubNanoseconds()
FAIL
FAIL	github.com/dromara/carbon/v2	0.006s
FAIL
```

I suspect the reason is the fact that I am on a time zone different from the test's author. My time zone:

```go
$ timedatectl
               Local time: Do 2024-12-12 21:45:43 CET
           Universal time: Do 2024-12-12 20:45:43 UTC
                 RTC time: Do 2024-12-12 21:45:44
                Time zone: Europe/Berlin (CET, +0100)
```

### PR DESCRIPTION
**Pull request by ccoVeille**
- **tests: Playing with Carbon Default is dangerous.**
- **ci: tests were written by someone in PRC timezone**

Fixes #268

### CODE REVIEW

**Comment by ccoVeille** [comment]
@gouguoyin could you review?

**Comment by gouguoyin** [comment]
> @gouguoyin could you review?

Yes, but there are too many changes. I need to verify carefully

**Comment by gouguoyin** [comment]
Actions failed

**Comment by ccoVeille** [comment]
You mean the golangci-lint one?

Yes, there are still many issues reported by linters. But there are not related to the PR, no ?

**Comment by gouguoyin** [comment]
https://github.com/dromara/carbon/actions/runs/12556501202/job/35007822745
image

**Comment by ccoVeille** [comment]
Unfortunately, I don't have a computer set up for dev with me, right now.

I'm unsure why tests were not failing earlier.

**Pull request merged**
