### PR TITLE
re translate README.jp

### PR DESCRIPTION
**Pull request by You-saku**
I re translate ```README.jp``` by myself.
ref: **https://github.com/dromara/carbon/issues/257**

### CODE REVIEW

**Comment by gouguoyin** [comment]
Thanks for your contribution

**Comment by You-saku** [comment]
Thanks to merged this pull request.
I try to contribute this project by go code later.  👍

**Comment by gouguoyin** [comment]
The translation here seems to be inconsistent
image

**Comment by You-saku** [comment]
@gouguoyin 
Sorry... There was an oversight. 🙇‍♂️ 
I will fix it and create another pull request.

**Comment by gouguoyin** [comment]
If possible, please provide `README.jp.md` for my other project [dongle](https://github.com/dromara/dongle), thank you very much.

**Comment by You-saku** [comment]
@gouguoyin 

I understand. I'll try to find time to translate others 👍 
By the way, do you have any high priority projects?

Also, as I said before, I would like to contribute to your projects with go code, I'm new to gopher, but if there is any development I can do, please share the link 🙏 
I will try to check out projects by myself too.

**Comment by You-saku** [comment]
@gouguoyin 
Long time, no chat !

> If possible, please provide README.jp.md for my other project [dongle](https://github.com/dromara/dongle), thank you very much.

I will try to translate into Japanese by myself.I'm sorry I misread your English before and gave you the wrong reply. 🙏 
Just in case, I created issue in that repository.
https://github.com/dromara/dongle/issues/23

**Pull request merged**
